project:
  type: website

website:
  title: "Ecologie, data en meer"
  navbar:
    right:
      - index.qmd
      - boeken.qmd
      - about.qmd
      - icon: github
        href: https://github.com/RedTent
format:
  html:
    theme: cosmo
    css: styles.css



