project:
  type: website
  output-dir: docs

website:
  title: "Ecologie, data en meer"
  navbar:
    right:
      - index.qmd
      - boeken.qmd
      - packages.qmd
      - about.qmd
      - icon: github
        href: https://github.com/RedTent
format:
  html:
    theme: 
      light: sandstone
      dark: slate
    css: styles.css



